security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\UserAuthAuthenticator
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _email
                password_parameter: _password
                enable_csrf: true
                default_target_path: /profile/principale/{id}
                always_use_default_target_path: false

            logout:
                path: /logout
                target: /login  

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
       
monolog:

    channels: [security]
