security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            logout:
                path: app_logout  # Make sure this matches the route in SecurityController
                target: app_login # Redirect to login after logout

 

        oauth:
            pattern: ^/oauth/check
            stateless: true
            provider: app_user_provider
    access_control:
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
