security:
    # Définir un provider d'utilisateur pour le firewall
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # ou 'username', selon votre structure

    # Utilisation de password_hashers au lieu de encoders
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    # Firewalls
    firewalls:
        main:
            # Connexion via un formulaire
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: home
            # Définir le provider d'utilisateur
            provider: app_user_provider
            logout:
                path: /logout
                target: home

    # Contrôle d'accès
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
