framework:
    validation:
        email_validation_mode: html5
        auto_mapping:
            App\Entity\: []  # Décommente cette ligne pour activer l'auto-mapping

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
