security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false
        login:
            pattern: ^/login
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            # Define your custom authenticator as the entry point
            entry_point: App\Security\UserAuthAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _email
                password_parameter: _password
                enable_csrf: true
                default_target_path: /profile/principale/{id}  # Redirige vers la page souhaitée après la connexion
                always_use_default_target_path: false  # 🔹 Force la redirection après login


            logout:
                 path: /logout
                 target: /login  # Ensure this route exists
           # custom_authenticator: App\Security\UserAuthAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # Uncomment the next line to always enable "remember me" by default
                # always_remember_me: true

    access_control:
        # Protect routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow access to profiler for everyone in dev mode

        

monolog:
    channels: [security]
