controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

google_login:
    path: /connect/google
    controller: App\Controller\UserController::connectGoogle

connect_google_check:
    path: /connect/google/check

app_login:
    path: /login
    controller: App\Controller\UserController::login

app_profile_principale:
    path: /profile/principale/{id}
    controller: App\Controller\UserController::profilePrincipale
    requirements:
        id: \d+  # Ensure 'id' is a number
