parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    images_directory_salle: '%kernel.project_dir%/public/uploads/salle'
    images_directory_activite: '%kernel.project_dir%/public/uploads/activite'
    images_directory_product: '%kernel.project_dir%/public/uploads/product'
    images_directory_evenement: '%kernel.project_dir%/public/uploads/evenement'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'

services:
    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Injection automatique des dépendances.
        autoconfigure: true # Enregistrement automatique des services comme commandes, événements, etc.
        
    # Enregistrement des contrôleurs (si vous avez des contrôleurs spécifiques)
    App\Controller\LogoutEventSubscriberController:
        tags:
            - { name: 'kernel.event_subscriber' }

    # Les classes dans src/ disponibles en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
