# config/services.yaml

parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    images_directory_salle: '%kernel.project_dir%/public/uploads/salle'
    images_directory_activite: '%kernel.project_dir%/public/uploads/activite'
    images_directory_product: '%kernel.project_dir%/public/uploads/product'
    images_directory_evenement: '%kernel.project_dir%/public/uploads/evenement'

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique des services (commandes, événements, etc.)

    # Enregistrement des contrôleurs
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Enregistrement du service de gestion des événements de déconnexion
    App\Controller\LogoutEventSubscriberController:
        tags:
            - { name: 'kernel.event_subscriber' }

    # Rendre les classes de src/ disponibles en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Enregistrement du GoogleAuthenticator
    App\Security\GoogleAuthenticator:
        arguments:
            $client: '@knpu.oauth2.client.google'
            $router: '@router'

    # Enregistrement du UserRepository
    App\Repository\UserRepository:
        autowire: true
