parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    mailer_dsn: '%env(MAILER_DSN)%'
services:
    Symfony\Component\Mailer\Transport\TransportInterface:
        factory: 'Symfony\Component\Mailer\Transport\TransportFactoryInterface::fromDsn'
        arguments:
            - '%mailer_dsn%'
    
    Symfony\Component\Mailer\Mailer:
        arguments:
            $transport: '@Symfony\Component\Mailer\Transport\TransportInterface'
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # ✅ Register AbstractOAuthAuthenticator (ensure it's correctly injected)
    App\Security\AbstractOAuthAuthenticator:
        abstract: true
        arguments:
            $clientRegistry: '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            $router: '@router'
            $repository: '@App\Repository\UserRepository'

    # ✅ Register GoogleAuthenticator
    App\Security\GoogleAuthenticator:
        parent: App\Security\AbstractOAuthAuthenticator

# config/services.yaml
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%kernel.project_dir%/public/uploads/photos'

